[package]
name = "dllinjector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = {version = "0.3.9", features = ["tlhelp32", "impl-default", "handleapi"]}
egui = "0.19.0"
eframe = "0.19.0"